export const DEFAULT_GENRES = [
  { name: 'Adventure' },
  { name: 'Comedy' },
  { name: 'Crime' },
  { name: 'Drama' },
  { name: 'Fantasy' },
  { name: 'Historical' },
  { name: 'Horror' },
  { name: 'Isekai' },
  { name: 'Mecha' },
  { name: 'Medical' },
  { name: 'Mystery' },
  { name: 'Philosophical' },
  { name: 'Psychological' },
  { name: 'Romance' },
  { name: 'Sports' },
  { name: 'Superhero' },
  { name: 'Thriller' },
  { name: 'Tragedy' },
];
